version: "3.9"

services:
  ai-aggregator:
    build: .
    container_name: ai-aggregator
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    restart: unless-stopped
